<script setup lang="ts">
import { onBeforeUnmount, onMounted, onUnmounted } from 'vue'
import Wrapper from './layouts/Wrapper.vue'
import { useStudentStore } from './stores/students'
import storage from './utils/storage'
import { usePetStore } from './stores/pets'
import { useTaskStore } from './stores/tasks'

const stuStore = useStudentStore()
const petStore = usePetStore()
const taskStore = useTaskStore()

const handleBeforeUnload = () => {
  storage.set('students', stuStore.students)
  storage.set('pets', petStore.pets)
  storage.set('tasks', taskStore.tasks)
}

onMounted(() => {
  // const stus = [
  //   {
  //     id: 1,
  //     name: '尉迟瑜柏',
  //     pets: [
  //       {
  //         id: 22,
  //         petId: 6,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 2,
  //     name: '富泰',
  //     pets: [
  //       {
  //         id: 9,
  //         petId: 6,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 3,
  //     name: '吉萱雯',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 4,
  //     name: '袁智',
  //     pets: [
  //       {
  //         id: 1,
  //         petId: 7,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 5,
  //     name: '任帆',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 6,
  //     name: '惠嘉',
  //     pets: [
  //       {
  //         id: 8,
  //         petId: 6,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 7,
  //     name: '蒙奇鑫',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 8,
  //     name: '公西瑶',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 9,
  //     name: '马玥哲',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 10,
  //     name: '伍昊旭',
  //     pets: [
  //       {
  //         id: 2,
  //         petId: 7,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 11,
  //     name: '鬱勇精',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 12,
  //     name: '公西然娴',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 13,
  //     name: '裴朗',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 14,
  //     name: '卜涛雪',
  //     pets: [
  //       {
  //         id: 5,
  //         petId: 3,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 15,
  //     name: '桂宇',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 16,
  //     name: '寿颖旭',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 17,
  //     name: '糜好刚',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 18,
  //     name: '芮芳',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 19,
  //     name: '狄巧娟',
  //     pets: [
  //       {
  //         id: 3,
  //         petId: 5,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 20,
  //     name: '荣妙',
  //     pets: [
  //       {
  //         id: 23,
  //         petId: 7,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 21,
  //     name: '欧泰',
  //     pets: [
  //       {
  //         id: 10,
  //         petId: 2,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 22,
  //     name: '步澈',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 23,
  //     name: '帅月莹',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 24,
  //     name: '后建',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 25,
  //     name: '屈清',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 26,
  //     name: '公冶琳',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 27,
  //     name: '寿欣',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 28,
  //     name: '季雷',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 29,
  //     name: '屠娟玲',
  //     pets: [
  //       {
  //         id: 4,
  //         petId: 6,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 30,
  //     name: '鄂学川',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 31,
  //     name: '焦笑',
  //     pets: [
  //       {
  //         id: 6,
  //         petId: 5,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 32,
  //     name: '乔倩',
  //     pets: [
  //       {
  //         id: 7,
  //         petId: 3,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 33,
  //     name: '游睿洁',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 34,
  //     name: '元璐',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 35,
  //     name: '於远霓',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 36,
  //     name: '钭伟波',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 37,
  //     name: '鄂才飞',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 38,
  //     name: '轩辕雨善',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 39,
  //     name: '奚健',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 40,
  //     name: '景泰',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 41,
  //     name: '莫飞',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 42,
  //     name: '栾义',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 43,
  //     name: '吉婉',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 44,
  //     name: '端木芳',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 45,
  //     name: '苍航',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 46,
  //     name: '公孙莉',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 47,
  //     name: '康帆',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 48,
  //     name: '古良慧',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 49,
  //     name: '胥梅',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 50,
  //     name: '公孙薇海',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 51,
  //     name: '廖洋美',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 52,
  //     name: '宁慧',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 53,
  //     name: '班辰香',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 54,
  //     name: '法旭',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 55,
  //     name: '濮晨芬',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 56,
  //     name: '法欣',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 57,
  //     name: '双妍',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 58,
  //     name: '乔舟健',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 59,
  //     name: '董驰嘉',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 60,
  //     name: '厉程',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 61,
  //     name: '翁彩德',
  //     pets: [
  //       {
  //         id: 21,
  //         petId: 5,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 62,
  //     name: '逄萌慧',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 63,
  //     name: '左丘梅',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 64,
  //     name: '茹怡泽',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 65,
  //     name: '宗英',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 66,
  //     name: '邹玥玉',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 67,
  //     name: '羊泽雨',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 68,
  //     name: '帅帅',
  //     pets: [
  //       {
  //         id: 19,
  //         petId: 6,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 69,
  //     name: '阴瑜',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 70,
  //     name: '钟离旭颖',
  //     pets: [
  //       {
  //         id: 20,
  //         petId: 3,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 71,
  //     name: '羿嘉',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 72,
  //     name: '班璐睿',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 73,
  //     name: '禹莉源',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 74,
  //     name: '焦枫',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 75,
  //     name: '桓博亮',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 76,
  //     name: '甘超',
  //     pets: [
  //       {
  //         id: 15,
  //         petId: 7,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 77,
  //     name: '赵丹',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 78,
  //     name: '焦淑雅',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 79,
  //     name: '金然',
  //     pets: [
  //       {
  //         id: 18,
  //         petId: 7,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 80,
  //     name: '屈妍',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 81,
  //     name: '花驰阳',
  //     pets: [
  //       {
  //         id: 17,
  //         petId: 4,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 82,
  //     name: '国寿',
  //     pets: [
  //       {
  //         id: 16,
  //         petId: 7,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 83,
  //     name: '公梅霜',
  //     pets: [
  //       {
  //         id: 14,
  //         petId: 4,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 84,
  //     name: '伯萱',
  //     pets: [
  //       {
  //         id: 12,
  //         petId: 7,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 85,
  //     name: '衡悦',
  //     pets: [
  //       {
  //         id: 11,
  //         petId: 5,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 86,
  //     name: '佴江鑫',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 87,
  //     name: '福泽',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 88,
  //     name: '吴雅超',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 89,
  //     name: '隆鹏辰',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 90,
  //     name: '后星',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 91,
  //     name: '骆康舟',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 92,
  //     name: '东郭智泽',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 93,
  //     name: '成雷',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 94,
  //     name: '袁曦',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 95,
  //     name: '孙柏',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 96,
  //     name: '霍慧谦',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 97,
  //     name: '常波',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 98,
  //     name: '易亮娟',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 99,
  //     name: '邵瑜',
  //     pets: [],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  //   {
  //     id: 100,
  //     name: '靳宇敏',
  //     pets: [
  //       {
  //         id: 13,
  //         petId: 6,
  //         level: 0,
  //       },
  //     ],
  //     coin: 0,
  //     receivedGifts: [],
  //     sendGifts: [],
  //     tasks: [],
  //   },
  // ]

  // const sts = stus.map((e) => ({ ...e, pets: [] }))
  // storage.set('students', sts)

  const students = storage.get('students')
  if (students) {
    stuStore.setStudents(students)
  }

  const pets = storage.get('pets')
  if (pets) {
    petStore.setPets(pets)
  }

  const maxPetId = storage.get('maxPetId')
  if (maxPetId) {
    petStore.setMaxPetId(maxPetId)
  }

  const tasks = storage.get('tasks')
  if (tasks) {
    taskStore.setTasks(tasks)
  }

  const maxTaskId = storage.get('maxTaskId')
  if (maxTaskId) {
    taskStore.setMaxTaskId(maxPetId)
  }

  window.addEventListener('beforeunload', handleBeforeUnload)
})

onUnmounted(() => {
  window.removeEventListener('beforeunload', handleBeforeUnload)
})
</script>

<template>
  <Wrapper />
</template>

<style scoped></style>
